_base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('outcomes/', include('outcomes.urls')),
    path('tasks/', include('tasks.urls')),
    path('', include('user.urls')),
]

tasks/urls.py
from django.urls import path

from tasks.views.classic.create import ClassicCreateView
from tasks.views.classic.delete import ClassicDeleteView
from tasks.views.classic.update import ClassicUpdateView

from tasks.views.count.create import CountCreateView
from tasks.views.count.update import CountUpdateView
from tasks.views.count.delete import CountDeleteView

from tasks.views.time.create import TimeCreateView
from tasks.views.time.update import TimeUpdateView
from tasks.views.time.delete import TimeDeleteView

from tasks.views.deadline.create import DeadlineCreateView
from tasks.views.deadline.delete import DeadlineDeleteView
from tasks.views.deadline.status import DeadlineStatus
from tasks.views.deadline.update import DeadlineUpdateView
from tasks.views.deadline.abort import DeadlineAbortView
from tasks.views.deadline.repeat import DeadlineRepeatView


urlpatterns = [
    path('<int:pk>/classic/create/', ClassicCreateView.as_view(), name='classic_create'),
    path('classic/<int:pk>/delete/', ClassicDeleteView.as_view(), name='classic_delete'),
    path('classic/<int:pk>/update/', ClassicUpdateView.as_view(), name='classic_update'),

    path('<int:pk>/count/create/', CountCreateView.as_view(), name='count_create'),
    path('count/<int:pk>/update/', CountUpdateView.as_view(), name='count_update'),
    path('count/<int:pk>/delete/', CountDeleteView.as_view(), name='count_delete'),

    path('<int:pk>/time/create/', TimeCreateView.as_view(), name='time_create'),
    path('time/<int:pk>/update/', TimeUpdateView.as_view(), name='time_update'),
    path('time/<int:pk>/delete/', TimeDeleteView.as_view(), name='time_delete'),

    path('<int:pk>/deadline/create/', DeadlineCreateView.as_view(), name='deadline_create'),
    path('deadline/<int:pk>/delete/', DeadlineDeleteView.as_view(), name='deadline_delete'),
    path('deadline/<int:pk>/status/', DeadlineStatus.as_view(), name='deadline_status'),
    path('deadline/<int:pk>/update/', DeadlineUpdateView.as_view(), name='deadline_update'),
    path('deadline/<int:pk>/abort/', DeadlineAbortView.as_view(), name='deadline_abort'),
    path('deadline/<int:pk>/repeat/', DeadlineRepeatView.as_view(), name='deadline_repeat'),

]

user/urls.py
from django.urls import path
from .views import UserProfileView


urlpatterns = [
    path('', UserProfileView.as_view(), name='profile'),
]

tasks/models/classic.py
from django.db import models
import datetime


class Classic(models.Model):

    outcome = models.ForeignKey(
        'outcomes.Outcome',
        models.CASCADE,
        related_name='classic_tasks',
        null=False,
        blank=False
    )

    description = models.TextField(null=False, blank=False)
    report = models.CharField(max_length=1024, null=True, blank=True)
    xp = models.IntegerField(default=0)
    is_done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    done_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.is_done and not self.done_at:
            self.done_at = datetime.datetime.now()

        if self.is_done:
            self.outcome.last_task_done_at = datetime.datetime.now()

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.outcome} | {self.description} xp: {self.xp} is done: {self.is_done}'

tasks/models/classic_task.py
from django.db import models
import datetime


class ClassicTask(models.Model):

    outcome = models.ForeignKey(
        'abilities.Outcome',
        models.SET_NULL,
        related_name='classic_tasks',
        null=True,
        blank=True
    )

    description = models.CharField(max_length=512)
    report = models.CharField(max_length=1024, null=True)
    xp = models.IntegerField(default=0)
    is_done = models.BooleanField(default=False)
    is_added = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    done_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.is_done and not self.done_at:
            self.done_at = datetime.datetime.now()

        if self.is_added is False and self.is_done is True:
            if self.outcome:
                self.outcome.total_xp += self.xp
                self.outcome.save()
            self.is_added = True

        if self.is_done:
            self.outcome.last_task_done_at = datetime.datetime.now()

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.outcome} | {self.description} xp: {self.xp} is done: {self.is_done}'

tasks/models/count.py
import datetime

from django.db import models


class Count(models.Model):
    outcome = models.ForeignKey(
        'outcomes.Outcome',
        models.CASCADE,
        related_name='count_tasks',
        null=False,
        blank=False,
    )

    description = models.CharField(max_length=256)
    xp = models.IntegerField(default=0)
    total_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    last_submit = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.outcome} | {self.description} xp: {self.total_count * self.xp}'

    def save(self, *args, **kwargs):
        self.last_submit = datetime.datetime.now()
        super().save(*args, **kwargs)

tasks/models/count_task.py
import datetime

from django.db import models


class CountTask(models.Model):
    outcome = models.ForeignKey(
        'abilities.Outcome',
        models.SET_NULL,
        related_name='count_tasks',
        null=True,
        blank=True,
    )

    description = models.CharField(max_length=256)
    xp = models.IntegerField(default=0)
    total_count = models.IntegerField(default=2)
    created_at = models.DateTimeField(auto_now_add=True)
    last_submit = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.outcome} | {self.description} xp: {self.total_count * self.xp}'

    def save(self, *args, **kwargs):
        self.last_submit = datetime.datetime.now()
        super().save(*args, **kwargs)

tasks/models/task.py
from django.db import models
from abilities.models.outcome import Outcome
import datetime


class Task(models.Model):

    outcome = models.ForeignKey(
        Outcome,
        on_delete=models.SET_NULL,
        related_name='tasks_outcome',
        null=True,
        blank=True
    )

    description = models.CharField(max_length=512)
    report = models.CharField(max_length=1024, null=True)
    xp = models.IntegerField(default=0)
    is_done = models.BooleanField(default=False)
    is_added = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    done_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.is_done and not self.done_at:
            self.done_at = datetime.datetime.now()

        if self.is_added is False and self.is_done is True:
            if self.outcome:
                self.outcome.total_xp += self.xp
                self.outcome.save()
            self.is_added = True

        if self.is_done:
            self.outcome.last_task_done_at = datetime.datetime.now()

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.outcome} | {self.description} xp: {self.xp} is done: {self.is_done}'

tasks/forms/classic.py
from django import forms

from tasks.models.classic import Classic


class ClassicCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs['class'] = 'desc-input'
        self.fields['description'].widget.attrs['placeholder'] = 'Describe Your Task..'
        self.fields['description'].widget.attrs['cols'] = '0'
        self.fields['description'].widget.attrs['rows'] = '0'

        self.fields['xp'].widget.attrs['class'] = 'xp-input-elem'

        self.fields['outcome'].required = False

    class Meta:
        model = Classic
        fields = ['description', 'xp', 'outcome']


class ClassicUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['report'].widget.attrs['class'] = 'desc-input'
        self.fields['report'].widget.attrs['placeholder'] = 'How things went on? the result, ' \
                                                            'the process, next step, etc,.'
        self.fields['report'].widget.attrs['cols'] = '0'
        self.fields['report'].widget.attrs['rows'] = '0'

    class Meta:
        model = Classic
        fields = [
            'report'
        ]

tasks/forms/classic_task.py
from django import forms

from tasks.models.classic_task import ClassicTask


class ClassicTaskCreateForm(forms.ModelForm):
    class Meta:
        model = ClassicTask
        fields = ['outcome', 'description', 'xp']


class ClassicTaskUpdateForm(forms.ModelForm):
    class Meta:
        model = ClassicTask
        fields = [
            'report'
        ]

tasks/forms/count.py
from django import forms

from tasks.models.count import Count


class CountCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs['class'] = 'desc-input'
        self.fields['description'].widget.attrs['placeholder'] = 'Describe Your Task..'
        self.fields['description'].widget.attrs['cols'] = '0'
        self.fields['description'].widget.attrs['rows'] = '0'

        self.fields['xp'].widget.attrs['class'] = 'xp-input-elem'

        self.fields['outcome'].required = False

    class Meta:
        model = Count
        fields = ['outcome', 'description', 'xp']


class CountUpdateForm(forms.Form):
    count = forms.CharField(label='count', max_length=5)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['count'].widget.attrs['class'] = 'xp-input-elem'

tasks/forms/count_task.py
from django import forms

from tasks.models.count_task import CountTask


class CountTaskCreateForm(forms.ModelForm):
    class Meta:
        model = CountTask
        fields = ['outcome', 'description', 'xp']


class CountTaskUpdateForm(forms.Form):
    count = forms.CharField(label='count', max_length=5)

tasks/forms/deadline.py
from datetime import timedelta
from django.utils import timezone
from django import forms

from tasks.models.deadline import Deadline


class DeadlineCreateForm(forms.ModelForm):
    duration_days = forms.IntegerField(required=False)
    duration_hours = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs['class'] = 'desc-input'
        self.fields['description'].widget.attrs['placeholder'] = 'Describe Your Task..'
        self.fields['description'].widget.attrs['cols'] = '0'
        self.fields['description'].widget.attrs['rows'] = '0'

        self.fields['xp'].widget.attrs['class'] = 'xp-input-elem'
        self.fields['penalty'].widget.attrs['class'] = 'xp-input-elem'

        self.fields['duration_days'].widget.attrs['class'] = 'xp-input-elem'
        self.fields['duration_hours'].widget.attrs['class'] = 'xp-input-elem'
        self.fields['deadline_date'].widget.attrs['class'] = 'xp-input-elem'

    class Meta:
        model = Deadline
        fields = ['description', 'xp', 'penalty', 'deadline_date']
        widgets = {
            'deadline_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        deadline_date = cleaned_data.get('deadline_date')
        duration_days = cleaned_data.get('duration_days')
        duration_hours = cleaned_data.get('duration_hours')

        if not deadline_date and (duration_days is None and duration_hours is None):
            raise forms.ValidationError("You must specify either a deadline date or a duration.")

        if deadline_date and (duration_days is not None or duration_hours is not None):
            raise forms.ValidationError("You can only specify a deadline date or a duration, not both.")

        if not deadline_date and (duration_days or duration_hours):
            now = timezone.now()
            days = duration_days or 0
            hours = duration_hours or 0
            cleaned_data['deadline_date'] = now + timedelta(days=days, hours=hours)

        return cleaned_data


class DeadlineUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['report'].widget.attrs['class'] = 'desc-input'
        self.fields['report'].widget.attrs['placeholder'] = 'How things went on? the result, ' \
                                                            'the process, next step, etc,.'
        self.fields['report'].widget.attrs['cols'] = '0'
        self.fields['report'].widget.attrs['rows'] = '0'

    class Meta:
        model = Deadline
        fields = ['report']


class DeadlineRepeatForm(forms.ModelForm):
    duration_days = forms.IntegerField(required=False)
    duration_hours = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['duration_days'].widget.attrs['class'] = 'xp-input-elem'
        self.fields['duration_hours'].widget.attrs['class'] = 'xp-input-elem'
        self.fields['deadline_date'].widget.attrs['class'] = 'xp-input-elem'

    class Meta:
        model = Deadline
        fields = ['deadline_date', 'duration_days', 'duration_hours']
        widgets = {
            'deadline_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        deadline_date = cleaned_data.get('deadline_date')
        duration_days = cleaned_data.get('duration_days')
        duration_hours = cleaned_data.get('duration_hours')

        if not deadline_date and (duration_days is None and duration_hours is None):
            raise forms.ValidationError("You must specify either a deadline date or a duration.")

        if deadline_date and (duration_days is not None or duration_hours is not None):
            raise forms.ValidationError("You can only specify a deadline date or a duration, not both.")

        if not deadline_date and (duration_days or duration_hours):
            now = timezone.now()
            days = duration_days or 0
            hours = duration_hours or 0
            deadline_date = now + timedelta(days=days, hours=hours)

        cleaned_data['deadline_date'] = deadline_date
        return cleaned_data

tasks/forms/deadline_task.py
from django import forms
from tasks.models.deadline_task import DeadlineTask


class DeadlineTaskCreateForm(forms.ModelForm):
    class Meta:
        model = DeadlineTask
        fields = ['description', 'xp', 'penalty', 'deadline_date', 'duration_days', 'duration_hours']
        widgets = {
            'deadline_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        deadline_date = cleaned_data.get('deadline_date')
        duration_days = cleaned_data.get('duration_days')
        duration_hours = cleaned_data.get('duration_hours')

        if not deadline_date and (duration_days is None and duration_hours is None):
            raise forms.ValidationError("You must specify either a deadline date or a duration.")

        if deadline_date and (duration_days is not None or duration_hours is not None):
            raise forms.ValidationError("You can only specify a deadline date or a duration, not both.")

        return cleaned_data


class DeadlineTaskUpdateForm(forms.ModelForm):
    class Meta:
        model = DeadlineTask
        fields = ['report']


class DeadlineTaskAbortForm(forms.ModelForm):
    class Meta:
        model = DeadlineTask
        fields = ['is_aborted']

class DeadlineTaskUpdateForm(forms.ModelForm):
    class Meta:
        model = DeadlineTask
        fields = ['report']

tasks/forms/task_done.py
from django import forms
from tasks.models.normal_task import NormalTask


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = NormalTask
        fields = [
            'report'
        ]

tasks/forms/time.py
from django import forms

from tasks.models.time import Time


class TimeCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs['class'] = 'desc-input'
        self.fields['description'].widget.attrs['placeholder'] = 'Describe Your Task..'
        self.fields['description'].widget.attrs['cols'] = '0'
        self.fields['description'].widget.attrs['rows'] = '0'

        self.fields['xp'].widget.attrs['class'] = 'xp-input-elem'

        self.fields['outcome'].required = False

    class Meta:
        model = Time
        fields = ['outcome', 'description', 'xp']


class TimeUpdateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['time'].widget.attrs['class'] = 'xp-input-elem'

    time = forms.CharField(label='time', max_length=5)

tasks/forms/time_task.py
from django import forms

from tasks.models.time_task import TimeTask


class TimeTaskCreateForm(forms.ModelForm):
    class Meta:
        model = TimeTask
        fields = ['outcome', 'description', 'xp']


class TimeTaskUpdateForm(forms.Form):
    time = forms.CharField(label='time', max_length=5)

tasks/templates/all_tasks.html
{% extends 'base.html'%}

{% block title %}
    Task List
{% endblock %}

{% block style %}
    body {
        font-family:monospace;
        background-color:#0d0d0d;
        color:#d9d9d9;
        font-size:1.5em;
    }

    .title{
        text-shadow:0px 3px 10px black;
    }
    .container{
        height:max-content;
        width:80%;
        min-width:600px;
        padding:20px;
        margin: 0 auto
    }

    .container .task {
        margin:20px;
        border:solid 1px purple;
        border-radius:6px;
        padding:20px;
        background-color:black;

    }

    .container .task .name{
        font-weight:bold;
        margin-bottom:10px;
        font-size:2em;
        text-align:center;
    }

    .container .task .xp{
        background: linear-gradient(blue, green, white);
        -webkit-background-clip: text; /* Clip text to background gradient */
        -webkit-text-fill-color: transparent; /* Set text color to transparent */
        margin-bottom:10px;
        font-size:1.2em;
        text-align:left;
    }

    .container .task .created{
        font-style:italic;
        color:white;
        text-align:right;
        font-size:0.7em;
    }

    .container .task .description{
        font-style:italic;
        color:white;
        text-align:left;
    }

    .container .task .status{
        color:white;
        text-align:right;
    }

    .create-task a{
        background: linear-gradient(#00cc66, #d24dff);
        -webkit-background-clip: text; /* Clip text to background gradient */
        -webkit-text-fill-color: transparent; /* Set text color to transparent */
        margin:10px;
        font-size:2em;
        transition:ease-in-out 0.5s;
    }

    .create-task {
        background-color:black;
        border: solid 1px purple;
        width:max-content;
        padding:20px;
        transition:ease-in-out 0.5s;
    }

    .create-task:hover {
        transition:ease-in-out 0.5s;
        border: solid 1px white;
        background-color:#0d0d0d;
        box-shadow:0px 0px 4px black;

    }

    .btn {
        text-decoration:none;
        color:gray;
        color:#d9d9d9;
        background-color:#0d0d0d;
        padding:5px;
        transition:ease-in-out 0.3s;
        box-shadow:0px 0px 2px purple;
    }

    .btn:hover {
        transition:ease-in-out 0.3s;
        color:black;
        background-color:black;
    }


{% endblock %}

{% block content %}
    <center>
        <h1 class="title">Tasks</h1>
        <div style="height:0.3em; width:12rem; background-color:purple;" ></div><br>
        <div style="height:0.3em; width:10rem; background-color:purple;" ></div><br>
        <div style="height:0.3em; width:8rem; background-color:purple;" ></div><br>
        <div style="height:0.3em; width:6rem; background-color:purple;" ></div><br>
        <div style="height:0.3em; width:4rem; background-color:purple;" ></div><br>
        <div style="height:1rem; width:1rem; background-color:purple; border-radius:2rem;" ></div><br>
        <div class="create-task">
            <a href="{% url 'task_create' %}">New Task</a>
        </div>
    </center>

    <div class="container">
        {% for task in tasks %}
            <div class="task">
                <div class="name">{{ task.outcome.name }}</div>
                <div class="xp">Points: {{ task.xp }}XP</div>
                <div class="description">{{ task.description }}</div>
                <div class="status">Status: {% if task.is_done %} Done {% else %} Not Done {% endif %}</div>
                {% if task.is_done %}
                    <div class="done">Done at: {{ task.done_at }}</div>
                {% endif %}
                <div class="created">Created at: {{ task.created_at }}</div>
                <a class="btn" href="{% url 'task_delete' task.pk %}" style="color:red;">Delete</a>
                <a class="btn" href="{% url 'task_detail' task.pk %}">Details</a>
                <a class="btn" href="{% url 'task_update' task.pk %}" style="color:green;">Update</a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

tasks/templates/task_confirm_delete.html
{% extends 'base.html'%}

{% block title %}
    Confirm Task Deletion
{% endblock %}

{% block style %}
    .box {
        font-family: monospace;
        background-color: #0d0d0d;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        text-align: center;
        background-color: black;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: white;
        margin-bottom: 10px;
    }

    p {
        color: #d9d9d9;
        margin-bottom: 20px;
    }

    button {
        padding: 10px 20px;
        background-color: purple;
        color: black;
        border: none;
        font-weight:bold;
        border-radius: 5px;
        cursor: pointer;
        transition:ease-in 0.3s;
    }

    button:hover {
        background-color: black;
        transition:ease-in 0.3s;

    }
    b{
        text-decoration:underline;
    }
{% endblock %}

{% block content %}
    <div class="box">
        <div class="container">
            <h1>Confirm Task Deletion</h1>
            <p>Are you sure you want to delete  <b>{{ object.description }}</b> with <b>{{ object.xp }} XP</b>?</p>

            <form method="post">
                {% csrf_token %}
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

tasks/templates/task_update.html
{% extends 'base.html'%}

{% block title %}
    Update Task as Done
{% endblock %}

{% block style %}
    .box {
        font-family: monospace;
        background-color: #0d0d0d;
        color: #d9d9d9;
        font-size: 1.5em;
    }

    .title {
        text-shadow: 0px 3px 10px black;
    }

    .container {
        height: max-content;
        width: 80%;
        min-width: 600px;
        padding: 20px;
        margin: 0 auto;
    }

    .form-container {
        margin-top: 20px;
        border: solid 1px purple;
        border-radius: 6px;
        padding: 20px;
        background-color: black;
    }

    .form-title {
        font-weight: bold;
        margin-bottom: 10px;
        font-size: 1.5em;
        text-align: center;
        text-shadow: 0px 0px 1px black, 0px 0px 4px purple, px 0px 7px gray;
    }

    .form-field {
        margin-bottom: 10px;
        font-size: 1em;
        text-align: left;
    }

    .form-submit {
        text-align: center;
    }

    .is-done {
        /* Increase the size of the checkbox */
        width: 20px;
        height: 20px;
        color:yellow;
        margin-right: 10px; /* Optional: Add some space between checkbox and label */
    }
    .btn {
        text-decoration:none;
        color:#d9d9d9;
        background-color:#0d0d0d;
        padding:10px;
        transition:ease-in-out 0.3s;
        box-shadow:0px 0px 10px purple;
        font-size:1.5rem;
    }

    .btn:hover {
        transition:ease-in-out 0.3s;
        color:black;
        background-color:black;
    }

{% endblock %}

{% block content %}
    <div class="box">
        <div class="container">
            <h1 class="title">Update Task as Done</h1>
            <div class="form-container">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-title">Mark Task as Done</div>
                    <div class="form-field">
                        <label for="id_is_done">Mark as Done:</label>
                        <input class="is-done" type="checkbox" id="id_is_done" name="is_done" {% if form.is_done.value %}checked{% endif %}>
                    </div>
                    <div class="form-submit">
                        <button type="submit" class="btn">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}